import "server-only";

import { generateText, gateway, Output } from "ai";
import { z } from "zod";
import { WiaDomainError } from "@/lib/wia-control/domain";
import { listControlDay, type WiaActor } from "@/lib/wia-control/service";
import { runGuardedAiCall } from "@/lib/ai/usage";
import { assertSafeAiOutput } from "@/lib/ai/evaluation";
import { isAiEnvironmentConfigured } from "@/lib/ai/governance";

const severitySchema = z.enum(["LOW", "MEDIUM", "HIGH", "CRITICAL"]);

const briefSchema = z.object({
  headline: z.string().trim().min(10).max(220),
  summary: z.string().trim().min(20).max(900),
  priorities: z.array(z.object({
    shiftId: z.string().trim().min(1),
    severity: severitySchema,
    reason: z.string().trim().min(10).max(360),
    recommendedAction: z.string().trim().min(10).max(360),
  })).max(12),
  draftMessage: z.string().trim().min(20).max(700),
});

export type OperationsBrief = z.infer<typeof briefSchema>;

type BriefFact = {
  shiftId: string;
  service: string;
  worksite: string;
  startsAt: string;
  status: string;
  openIncidents: Array<{ severity: string; type: string; dueAt?: string }>;
  hasClockIn: boolean;
  hasClockOut: boolean;
};

export const AI_BRIEF_MODEL = "openai/gpt-5.4-mini";

/**
 * Environment-level readiness only. Whether this particular workspace may call
 * AI is decided by the gate in governance.ts, which also enforces the company
 * feature flag, the kill switches, the rate limit, and the budget.
 */
export function isOperationsBriefEnabled() {
  return isAiEnvironmentConfigured();
}

function operationalFacts(day: Awaited<ReturnType<typeof listControlDay>>): BriefFact[] {
  return day.map((shift) => ({
    shiftId: shift.id,
    service: shift.service?.title ?? shift.title,
    worksite: shift.worksite.name,
    startsAt: shift.startsAt,
    status: shift.status,
    // The classification, not the wording. An incident title is generated by
    // the product today, but it is a text field on a record a human can reach,
    // and minimisation should not depend on that staying true.
    openIncidents: shift.incidents
      .filter((incident) => ["OPEN", "ACKNOWLEDGED"].includes(incident.status))
      .map((incident) => ({ severity: incident.severity, type: incident.type, dueAt: incident.dueAt })),
    hasClockIn: shift.clockEvents.some((event) => event.type === "CLOCK_IN"),
    hasClockOut: shift.clockEvents.some((event) => event.type === "CLOCK_OUT"),
  }));
}

export async function generateOperationsBrief(actor: WiaActor, date: string) {
  const facts = operationalFacts(await listControlDay(actor, date));
  const allowedShiftIds = facts.map((fact) => fact.shiftId);

  return runGuardedAiCall(
    {
      actor,
      feature: "operations_brief",
      model: AI_BRIEF_MODEL,
      entity: { entity: "OperationsBrief", entityId: date },
      metadata: { date, sourceShiftCount: facts.length },
    },
    async () => {
      const { output, usage } = await generateText({
        model: gateway(AI_BRIEF_MODEL),
        system:
          "You are WIAControl's operations assistant. Work only from the supplied facts. Do not claim legal compliance, make employment decisions, assign employees, or invent missing information. Your output is an internal draft that requires human approval. Use concise professional English.",
        prompt: `Create an operations brief for ${date}. Use only these tenant-scoped operational facts. Do not mention employee names, GPS coordinates, or data not supplied.
${JSON.stringify(facts)}`,
        output: Output.object({ schema: briefSchema, name: "operations_brief" }),
      });
      if (!output || output.priorities.some((priority) => !allowedShiftIds.includes(priority.shiftId))) {
        throw new WiaDomainError(
          "AI_INVALID_OUTPUT",
          "The brief referred to a shift that was not among the supplied facts."
        );
      }
      assertSafeAiOutput(
        [output.headline, output.summary, output.draftMessage, ...output.priorities.map((priority) => `${priority.reason} ${priority.recommendedAction}`)].join("\n"),
        { allowedIds: allowedShiftIds }
      );
      return {
        result: output,
        tokens: {
          promptTokens: usage?.inputTokens ?? 0,
          completionTokens: usage?.outputTokens ?? 0,
        },
      };
    }
  );
}

export const __test__ = { operationalFacts };
